export let table = {
  tableName: 'news',
  comment: '蔬菜资讯',
  comments: '蔬菜资讯',
  sfsh: '否',
  authPeople: '否',
  emailRegister: '否',
  hasCart: '否',
  thumbsUp: '否',
  storeUp: '否',
  browseClick: '否',
  hasHot: '无',
  virtualPay: '否',
  selectSeat: '否',
  hasPay: '否',
  isReverse: '否',
  browseHistory: '否',
  limit: '否',
  vip: '否',
  jifen: '否',
  hasAlipay: '否',
  tplist: '是',
  groupBuy: '否',
  creditScore: '否',
  authSeparate: '否',
  discuss: '否',
  location: '否',
  sessionReadTable: '',
  merchantRole: '',
  homeSearch: '否',
  mapType: '无',
  hasChapter: '无',
  hasAuction: '否',
  hasMusic: '否',
  sharePlatform: '',
  hasChat: '无',
  collaborativeAction: '',
  fkMainTable: '',
  status: '0',
  crossOptTableName: [],
  crossOptButton: [],
  crossOptAudit: [],
  crossOptPay: [],
  crossOptButtonStatusColumns: [],
  crossOptButtonTips: [],

  csuOperateList: [],
  csuTypeList: [],
  csuUpdateTableList: [],
  csuUpdateColumnList: [],
  csuUpdateColumnTypeList: [],
  csuUpdateColumnValueList: [],
  csuMessageList: [],
  csuConditionColumnList_1: [],  
  csuConditionColumnList_2: [],
    
}

export let columns = [
  {
    columnName: 'title',
    comments: '标题',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '否',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '是',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '16',
    detail_type: 'DetailTitle',
    detail_order: 2,
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'picture',
    comments: '图片',
    type: '图',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '否',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '是',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '16',
    table_type: 'TableImage',
    form_type: 'YyFile',
    form_accept: 'image/*',
    formMaxCount: 3,
    imageRecognize: false, 
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'introduction',
    comments: '简介',
    type: '多',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '16',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YyTextArea',
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'content',
    comments: '内容',
    type: '编',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '否',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '32',
    table_type: 'TableHtml',
    form_type: 'YyQuill',
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'name',
    comments: '发布人',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '16',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'headportrait',
    comments: '头像',
    type: '图',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    table_type: 'TableImage',
    form_type: 'YyFile',
    form_accept: 'image/*',
    formMaxCount: 1,
    imageRecognize: false, 
    form_hidden: false,    
    options: [],
  },
]

export let searchColumns = [
  {
    queryFlagInput: ['是'],
    columnName: 'title',
    comments: '标题',
    refTable: '',
    refColumn: '',
    placeholder: '标题',
    form_type: 'YyText', 
    options: [],
  },

]

export let headerButtons = [
  {
    title: '新增',
    name: '新增',
    key: 'add',
    iconName: 'Plus',
    className: 'action-add',
  },
]
export let tableButtons = []

export let detailConfig = {
  hasIsanon: false,
  titleName: 'title',
  titleNames: ['title'],
  titleHeads: [''],
  imgName: 'picture',
  imgNames: ['picture','headportrait'],
  pubPeopleName: '',
  sortName: '',
  sortOrder: 'desc',
  videoNames: [],
  inteltypeName: '',
  merchantName: '',
  payBtns: [
  ],
  hasBuyInput: false,
  actionBtns: [
    {
      title: '修改',    
      name: '修改',
      key: 'edit',
      iconName: 'Edit',
    },
    {
      title: '删除',
      name: '删除',
      key: 'remove',
      iconName: 'Delete',
    },
  ],
  tabs: [
    {
      name: 'TabQuill',
      columnName: 'content',
      label: '内容',
    },
  ],
  sortList: [
  ]  
}