
const chartData = [
  {
    tableName: 'orders',  
    xColumn: 'addtime',  
    api: 'orders/value/addtime/buynumber/日',  
    graphType: '横',  
    showHome: true,
    title: '日销量统计',  
    subNameList: [],  
    type: 'multiStatic',  
    typeSections: [],  
    hasMultiSeries: false,
    chartSort: '0',  
    func: '',  
    queryName: '',  
    queryRoles: [],  
  },
  {
    tableName: 'orders',  
    xColumn: 'addtime',  
    api: 'orders/value/addtime/buynumber/月',  
    graphType: '竖',  
    showHome: true,
    title: '月销量统计',  
    subNameList: [],  
    type: 'multiStatic',  
    typeSections: [],  
    hasMultiSeries: false,
    chartSort: '0',  
    func: '',  
    queryName: '',  
    queryRoles: [],  
  },
  {
    tableName: 'orders',  
    xColumn: 'goodname',  
    api: 'orders/value/goodname/buynumber',  
    graphType: '漏',  
    showHome: true,
    title: '商品销量',  
    subNameList: [],  
    type: 'multiStatic',  
    typeSections: [],  
    hasMultiSeries: false,
    chartSort: '0',  
    func: '',  
    queryName: '',  
    queryRoles: [],  
  },
  {
    tableName: 'orders',  
    xColumn: 'addtime',  
    api: 'orders/value/addtime/total/日',  
    graphType: '折滑面',  
    showHome: true,
    title: '日销额统计',  
    subNameList: [],  
    type: 'multiStatic',  
    typeSections: [],  
    hasMultiSeries: false,
    chartSort: '0',  
    func: '',  
    queryName: '',  
    queryRoles: [],  
  },
  {
    tableName: 'orders',  
    xColumn: 'addtime',  
    api: 'orders/value/addtime/total/月',  
    graphType: '竖',  
    showHome: true,
    title: '月销额统计',  
    subNameList: [],  
    type: 'multiStatic',  
    typeSections: [],  
    hasMultiSeries: false,
    chartSort: '0',  
    func: '',  
    queryName: '',  
    queryRoles: [],  
  },
  {
    tableName: 'orders',  
    xColumn: 'goodname',  
    api: 'orders/value/goodname/total',  
    graphType: '饼2',  
    showHome: true,
    title: '商品销售额',  
    subNameList: [],  
    type: 'multiStatic',  
    typeSections: [],  
    hasMultiSeries: false,
    chartSort: '0',  
    func: '',  
    queryName: '',  
    queryRoles: [],  
  },
]
export default chartData