export let table = {
  tableName: 'discusschanpinxinxi',
  comment: '',
  comments: '产品信息评论',
  sfsh: '',
  authPeople: '',
  emailRegister: '',
  hasCart: '',
  thumbsUp: '',
  storeUp: '',
  browseClick: '',
  hasHot: '',
  virtualPay: '',
  hasSales: false,
  selectSeat: '',
  hasPay: '',
  isReverse: '',
  browseHistory: '',
  limit: '',
  vip: '',
  jifen: '',
  hasAlipay: '',
  tplist: '',
  groupBuy: '',
  creditScore: '',
  authSeparate: '',
  discuss: '是',
  location: '',
  sessionReadTable: '',
  merchantRole: '',
  homeSearch: '',
  mapType: '',
  hasChapter: '',
  hasAuction: '',
  hasMusic: '',
  sharePlatform: '',
  hasChat: '',
  collaborativeAction: '',
  fkMainTable: '',
  status: '',
  conflictType: '',
  crossOptRole: '',
  sfshRole: '',
  payRole: '',
  titleName: '',
  couponType: '',
  couponType2: '',
  couponColumn: '',

  crossOptTableName: [],
  crossOptButton: [],
  crossOptAudit: [],
  crossOptPay: [],
  crossOptButtonStatusColumns: [],
  crossOptButtonTips: [],

  csuOperateList: [],
  csuTypeList: [],
  csuUpdateTableList: [],
  csuUpdateColumnList: [],
  csuUpdateColumnTypeList: [],
  csuUpdateColumnValueList: [],
  csuMessageList: [],
  csuConditionColumnList_1: [],  
  csuConditionColumnList_2: [],
    
}

export let columns = [
  {
    columnName: 'refid',
    comments: '关联表id',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '否',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '长',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '是',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    detail_type: 'DetailTitle',
    detail_order: 2,
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'userid',
    comments: '用户id',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '否',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '长',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '是',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'avatarurl',
    comments: '头像',
    type: '图',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    table_type: 'TableImage',
    form_type: 'YyFile',
    form_accept: 'image/*',
    formMaxCount: 3,
    imageRecognize: false, 
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'nickname',
    comments: '用户名',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'content',
    comments: '评论内容',
    type: '编',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '否',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    table_type: 'TableHtml',
    form_type: 'YyQuill',
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'score',
    comments: '评分',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '浮',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'reply',
    comments: '回复内容',
    type: '编',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '是',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    table_type: 'TableHtml',
    form_type: 'YyQuill',
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'thumbsupnum',
    comments: '赞',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '数',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '是',
    encryption: '',
    courseFlag: '',
    columnDefault: '0',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'crazilynum',
    comments: '踩',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '数',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '是',
    encryption: '',
    courseFlag: '',
    columnDefault: '0',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'istop',
    comments: '置顶',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '数',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '是',
    encryption: '',
    courseFlag: '',
    columnDefault: '0',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    table_type: 'TableSwitch',
    form_type: 'YySwitch',
    form_hidden: false,    
    options: [
      {
        value: 0,
        label: '否'
      },
      {
        value: 1,
        label: '是'
      },
    ],
  },
  {
    columnName: 'tuserids',
    comments: '赞用户ids',
    type: '多',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '是',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YyTextArea',
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'cuserids',
    comments: '踩用户ids',
    type: '多',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '是',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YyTextArea',
    form_hidden: false,    
    options: [],
  },
]

export let searchColumns = [
]

export let headerButtons = [
  {
    title: '新增',   
    name: '新增',
    key: 'add',
    iconName: 'Plus',
    className: 'action-add',
  },
]
export let tableButtons = []

/**
 * @description 课程表
 * titleNames: 标题
 * subTitleNames: 副标题
 * searchNames: 用权。显示的时候，根据这个条件过滤
 */ 
export let timeTable = {
  titleNames: [],
  subTitleNames: [],
  searchNames: []
}

export let detailConfig = {
  tableName: 'discusschanpinxinxi',
  hasIsanon: false,
  titleName: '',
  titleNames: [],
  titleHeads: [],
  imgName: '',
  imgNames: ['avatarurl'],
  pubPeopleName: '',
  sortName: '',
  sortOrder: 'desc',
  videoNames: [],
  inteltypeName: '',
  merchantName: '',
  payBtns: [
  ],
  hasBuyInput: false,
  actionBtns: [
    {
      title: '修改',    
      name: '修改',
      key: 'edit',
      iconName: 'Edit',
    },
    {
      title: '删除',
      name: '删除',
      key: 'remove',
      iconName: 'Delete',
    },
  ],
  tabs: [
    {
      name: 'TabQuill',
      columnName: 'content',
      label: '评论内容',
    },
    {
      name: 'TabQuill',
      columnName: 'reply',
      label: '回复内容',
    },
    {
      name: 'TabDiscuss',
      label: '评论',
    },
  ],
  sortList: [
  ]
}