export let table = {
  tableName: 'orders',
  comment: '',
  comments: '订单',
  sfsh: '否',
  authPeople: '否',
  emailRegister: '否',
  detail: '否',
  foreEndList: '否',
  foreEndAdd: '否',
  jifen: '否',
  isReverse: '否',
  hasCart: '否',
  limit: '否',
  mulGraphType: '',
  virtualPay: '否',
  hasSales: false,
  vip: '否',
  groupBuy: '否',
  creditScore: '否',
  authSeparate: '是',
  tplist: '否',
  addHomePage: '否',
  hasPay: '否',
  hasAlipay: '否',
  hasRegister: '否',
  thumbsUp: '否',
  discuss: '否',
  storeUp: '否',
  statistics: '',
  mulStatistics: '',
  selectSeat: '否',
  menuJump: '列表',
  browseClick: '否',
  browseHistory: '否',
  foreEndListAuth: '否',
  location: '否',
  isAdmin: '否',
  sessionReadTable: '',
  merchantRole: '',
  exportExcel: '是',
  importExcel: '否',
  hasPrint: '否',
  frontLogin: '是',
  frontRegister: '是',
  backLogin: '是',
  backRegister: '是',
  homeSearch: '否',
  mapType: '无',
  homeStatistic: '统计图',
  passwordProtected: '否',
  tabBar: '否',
  hasChapter: '无',
  hasAuction: '否',
  hasHot: '无',
  hasMusic: '否',
  sharePlatform: '',
  hasChat: '无',
  collaborativeAction: '',
  fkMainTable: '',
  fixedAuth: '',
  passwordWrongNum: '0',
  buttons: '',
  imagePath: '轮播图/果蔬',
  orderNum: '',
  status: '',
  conflictType: '',
  sortName: '',
  sortOrder: 'desc',
  titleName: '',
  couponType: '',

  crossOptTableName: [],
  crossOptButton: [],
  crossOptAudit: [],
  crossOptPay: [],
  crossOptButtonStatusColumns: [],
  crossOptButtonTips: [],

  csuOperateList: [],
  csuTypeList: [],
  csuUpdateTableList: [],
  csuUpdateColumnList: [],
  csuUpdateColumnTypeList: [],
  csuUpdateColumnValueList: [],
  csuMessageList: [],
  csuConditionColumnList_1: [],  
  csuConditionColumnList_2: [],
}


export let columns = [
  {
    columnName: 'orderid',
    comments: '订单编号',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '否',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '自',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'goodid',
    comments: '商品id',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '否',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '长',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'goodname',
    comments: '商品名称',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'picture',
    comments: '图片',
    type: '图',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '否',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    table_type: 'TableImage',
    form_type: 'YyFile',
    form_accept: 'image/*',
    formMaxCount: 3,
    imageRecognize: false, 
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'buynumber',
    comments: '购买数量',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '数',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'price',
    comments: '单价',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '浮',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'total',
    comments: '总价',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '浮',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'type',
    comments: '支付类型',
    type: '下',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '现金,积分',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '数',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '2,3,8,4,6,7',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    table_type: 'TableTag',
    form_type: 'YySingleSelect', 
    form_hidden: false,    
    options: [
      {
        value: 1,
        label: '余额',
        type: 'primary',
      },
      {
        value: 2,
        label: '积分',
        type: 'success',
      },
      {
        value: 3,
        label: '团购',
        type: 'warning',
      },
    ],     
  },
  {
    columnName: 'status',
    comments: '订单状态',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '未支付,已支付,已完成,已取消,已退款,已发货',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [
      {
        value: '未支付',
        label: '未支付',
      },
      {
        value: '已支付',
        label: '已支付',
      },
      {
        value: '已完成',
        label: '已完成',
      },
      {
        value: '已取消',
        label: '已取消',
      },
      {
        value: '已退款',
        label: '已退款',
      },
      {
        value: '已发货',
        label: '已发货',
      },
    ],
  },
  {
    columnName: 'address',
    comments: '地址',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'tel',
    comments: '电话',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'consignee',
    comments: '收货人',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'remark',
    comments: '备注',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'addtime',
    comments: '创建时间',
    type: '日长',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyDatePicker',
    form_showTime: true,
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'userid',
    comments: '用户id',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '长',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'tablename',
    comments: '商品表名',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '是',
    encryption: '',
    courseFlag: '',
    columnDefault: 'chanpinxinxi',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    table_type: 'TableName',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'logistics',
    comments: '物流',
    type: '编',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    table_type: 'TableHtml',
    form_type: 'YyQuill',
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'maijiazhanghao',
    comments: '商户名称',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: 'shangjia',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'sfsh',
    comments: '是否审核',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '是',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    table_type: 'TableTag',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [
      {
        value: '是',
        label: '已通过',
        type: 'success',
      },
      {
        value: '待审核',
        label: '待审核',
        type: 'info',
      },
      {
        value: '否',
        label: '未通过',
        type: 'danger',
      },
    ],
  },
  {
    columnName: 'shhf',
    comments: '审核回复',
    type: '多',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '是',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyTextArea',
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'role',
    comments: '用户角色',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    table_type: 'TableName',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'returnreason',
    comments: '退货原因',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
]

export let searchColumns = [
  {
    queryFlagInput: ['是'],
    columnName: 'orderid',
    comments: '订单编号',
    level: 0,
    refTable: '',
    refColumn: '',
    placeholder: '订单编号',
    form_type: 'YyText', 
    options: [],
  },
]
export let headerButtons = [
  {
    title: '新增',
    name: '新增',
    key: 'add',
    iconName: 'Plus',
    className: 'action-add',
  },
  {
    title: '删除',
    name: '删除',
    key: 'removes',
    iconName: 'Delete',
    className: 'action-removes',
  },
  {
    title: '导出',
    name: '导出',
    key: 'exportExcel',
    iconName: 'Download',
  },
  {
    title: '批量发货',
    name: '发货',
    key: 'deliverGood',
    iconName: '',
  },
  {
    title: '批量收货',
    name: '确认收货',
    key: 'comfirmReceipt',
    iconName: '',
  },
  {
    title: '日销量统计',
    name: '日销量统计',
    key: 'multi日销量统计',
    type: 'statis',
    iconName: 'DataAnalysis',
  },
  {
    title: '月销量统计',
    name: '月销量统计',
    key: 'multi月销量统计',
    type: 'statis',
    iconName: 'DataAnalysis',
  },
  {
    title: '商品销量',
    name: '商品销量',
    key: 'multi商品销量',
    type: 'statis',
    iconName: 'DataAnalysis',
  },
  {
    title: '日销额统计',
    name: '日销额统计',
    key: 'multi日销额统计',
    type: 'statis',
    iconName: 'DataAnalysis',
  },
  {
    title: '月销额统计',
    name: '月销额统计',
    key: 'multi月销额统计',
    type: 'statis',
    iconName: 'DataAnalysis',
  },
  {
    title: '商品销售额',
    name: '商品销售额',
    key: 'multi商品销售额',
    type: 'statis',
    iconName: 'DataAnalysis',
  },
]
export let tableButtons = [
  {
    title: '查看',
    name: '查看',
    key: 'view',
    iconName: 'View',
    className: 'action-view',
  },
  {
    title: '删除',
    name: '删除',
    key: 'remove',
    className: 'action-delete',
    iconName: 'Delete',
  },
  {
    title: '修改', 
    name: '修改',
    key: 'edit',
    className: 'action-edit',
    iconName: 'Edit',
  },

  {
    title: '物流',
    name: '物流',
    key: 'logistics',
    iconName: 'Van',
  },
  {
    title: '发货',
    name: '发货',
    key: 'deliverGood',
    iconName: '',
  },
  {
    title: '确认收货',
    name: '确认收货',
    key: 'comfirmReceipt',
    iconName: '',
  },
  {
    title: '退货审核',
    name: '退货审核',
    key: 'returnGoodSh',
    iconName: 'DocumentChecked',
  }, 
  {
    title: '二维码',
    name: '二维码',
    key: 'showQrCode',
    iconName: '',
  },
]

/**
 * @description 用权
 * titleNames: 标题
 * subTitleNames: 副标题
 * searchNames: 用权。显示的时候，根据这个条件过滤
 */ 
export let timeTable = {
  titleNames: [],
  subTitleNames: [],
  searchNames: []
}