export let table = {
  tableName: 'shangjia',
  comment: '',
  comments: '商家',
  sfsh: '是',
  authPeople: '是',
  emailRegister: '否',
  hasCart: '否',
  thumbsUp: '否',
  storeUp: '否',
  browseClick: '否',
  hasHot: '无',
  virtualPay: '否',
  hasSales: false,
  selectSeat: '否',
  hasPay: '否',
  isReverse: '否',
  browseHistory: '否',
  limit: '否',
  vip: '否',
  jifen: '否',
  hasAlipay: '否',
  tplist: '否',
  groupBuy: '否',
  creditScore: '否',
  authSeparate: '否',
  discuss: '否',
  location: '否',
  sessionReadTable: '',
  merchantRole: '',
  homeSearch: '否',
  mapType: '无',
  hasChapter: '无',
  hasAuction: '否',
  hasMusic: '否',
  sharePlatform: '',
  hasChat: '非好友',
  collaborativeAction: '',
  fkMainTable: '',
  status: '',
  conflictType: '',
  crossOptRole: '',
  sfshRole: '',
  payRole: '',
  titleName: '',
  couponType: '',
  couponType2: '',
  couponColumn: '',

  crossOptTableName: [],
  crossOptButton: [],
  crossOptAudit: [],
  crossOptPay: [],
  crossOptButtonStatusColumns: [],
  crossOptButtonTips: [],

  csuOperateList: [],
  csuTypeList: [],
  csuUpdateTableList: [],
  csuUpdateColumnList: [],
  csuUpdateColumnTypeList: [],
  csuUpdateColumnValueList: [],
  csuMessageList: [],
  csuConditionColumnList_1: [],  
  csuConditionColumnList_2: [],
    
}

export let columns = [
  {
    columnName: 'maijiazhanghao',
    comments: '卖家账号',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '否',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '去',
    loginUser: '是',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '16',
    detail_type: 'DetailTitle',
    detail_order: 2,
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'mima',
    comments: '密码',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '否',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyPassword',
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'maijiaxingming',
    comments: '姓名',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '否',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '16',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'yingyezhizhao',
    comments: '营业执照',
    type: '图',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '否',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    table_type: 'TableImage',
    form_type: 'YyFile',
    form_accept: 'image/*',
    formMaxCount: 3,
    imageRecognize: false, 
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'touxiang',
    comments: '头像',
    type: '图',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    table_type: 'TableImage',
    form_type: 'YyFile',
    form_accept: 'image/*',
    formMaxCount: 1,
    imageRecognize: false, 
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'xingbie',
    comments: '性别',
    type: '下',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '男,女',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YySingleSelect', 
    form_hidden: false,    
    options: [
      {
        value: '男',
        label: '男',
      },
      {
        value: '女',
        label: '女',
      },
    ],
  },
  {
    columnName: 'youxiang',
    comments: '邮箱',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '邮',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'lianxidianhua',
    comments: '手机',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '手',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'sfsh',
    comments: '是否审核',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '是',
    encryption: '',
    courseFlag: '',
    columnDefault: '待审核',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    detail_type: 'DetailTag',
    detail_order: 0,
    table_type: 'TableTag',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [
      {
        value: '是',
        label: '已通过',
        type: 'success',
      },
      {
        value: '待审核',
        label: '待审核',
        type: 'info',
      },
      {
        value: '否',
        label: '未通过',
        type: 'danger',
      },
    ],
  },
  {
    columnName: 'shhf',
    comments: '审核回复',
    type: '多',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '是',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    detail_type: 'DetailText',
    detail_order: 0,
    form_type: 'YyTextArea',
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'money',
    comments: '余额',
    type: '普',
    dateCurFlag: '',
    categoryFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    level: 0,
    isNullable: '',
    isReadonly: '',
    isReadonlyInput: '',
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '浮',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    tplist: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '是',
    encryption: '',
    courseFlag: '',
    columnDefault: '0',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
]

export let searchColumns = [
  {
    queryFlagInput: ['是'],
    columnName: 'maijiaxingming',
    comments: '姓名',
    level: 0,
    refTable: '',
    refColumn: '',
    placeholder: '姓名',
    form_type: 'YyText', 
    options: [],
  },

  {
    queryFlagInput: ['是'],
    columnName: 'sfsh',
    comments: '是否通过',
    form_type: 'YySingleSelect',
    placeholder: '是否通过',
    options:[
      {
        value: '是',
        label: '是'
      },
      {
        value: '否',
        label: '否'
      },
      {
        value: '待审核',
        label: '待审核'
      },
    ]
  },
]

export let headerButtons = [
  {
    title: '新增',   
    name: '新增',
    key: 'add',
    iconName: 'Plus',
    className: 'action-add',
  },
]
export let tableButtons = []

/**
 * @description 课程表
 * titleNames: 标题
 * subTitleNames: 副标题
 * searchNames: 用权。显示的时候，根据这个条件过滤
 */ 
export let timeTable = {
  titleNames: [],
  subTitleNames: [],
  searchNames: []
}

export let detailConfig = {
  tableName: 'shangjia',
  hasIsanon: false,
  titleName: '',
  titleNames: [],
  titleHeads: [],
  imgName: '',
  imgNames: ['yingyezhizhao','touxiang'],
  pubPeopleName: '',
  sortName: '',
  sortOrder: 'desc',
  videoNames: [],
  inteltypeName: '',
  merchantName: '',
  payBtns: [
  ],
  hasBuyInput: false,
  actionBtns: [
    {
      title: '修改',    
      name: '修改',
      key: 'edit',
      iconName: 'Edit',
    },
    {
      title: '删除',
      name: '删除',
      key: 'remove',
      iconName: 'Delete',
    },
    {
      title: '私聊',
      name: '私聊',
      key: 'chat',
      iconName: 'ChatLineSquare',
    },
    {
      title: '审核',
      name: '审核',
      key: 'sfsh',
      iconName: 'DocumentChecked',
    },
  ],
  tabs: [
  ],
  sortList: [
  ]
}